/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import Archivos.ManejoDeArchivos;
import Usuario.Singleton;

/**
 *
 * @author axeln
 */
public class SignIn_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignIn_SignUp
     */
    public SignIn_SignUp() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LoginActionLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        DisplayUsernameLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();
        TokenLabel = new javax.swing.JLabel();
        DisplayTokensLabel = new javax.swing.JLabel();
        CaballosGameButton = new javax.swing.JButton();
        BlackJackGameButton = new javax.swing.JButton();
        TragamonedasGameButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        MenuActionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        Title.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("CASINO");

        SignupButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        SignupButton.setText("Registrarse");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        UsernameTextField.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        UsernameTextField.setForeground(new java.awt.Color(153, 153, 153));
        UsernameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UsernameTextField.setText("AxelCas123");
        UsernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameTextFieldFocusGained(evt);
            }
        });
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PasswordTextField.setText("AxelCas123");
        PasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordTextFieldFocusGained(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PasswordLabel.setText("Contraseña:");
        PasswordLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        UsernameLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        UsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UsernameLabel.setText("Usuario:");
        UsernameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        LoginButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        LoginButton.setText("Iniciar Sesión");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginActionLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        LoginActionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LoginActionLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LoginActionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsernameTextField)
                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(SignupButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginActionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        MainPanel.add(LoginPanel, "card3");

        DisplayUsernameLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        DisplayUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DisplayUsernameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        WelcomeLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        WelcomeLabel.setText("Bienvenido");
        WelcomeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TokenLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        TokenLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TokenLabel.setText("Fichas:");
        TokenLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        DisplayTokensLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        DisplayTokensLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DisplayTokensLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        CaballosGameButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        CaballosGameButton.setText("Caballos");
        CaballosGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaballosGameButtonActionPerformed(evt);
            }
        });

        BlackJackGameButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        BlackJackGameButton.setText("BlackJack");
        BlackJackGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackJackGameButtonActionPerformed(evt);
            }
        });

        TragamonedasGameButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        TragamonedasGameButton.setText("Tragamonedas");
        TragamonedasGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TragamonedasGameButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        LogoutButton.setText("Cerrar sesión");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        MenuActionLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        MenuActionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MenuActionLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addComponent(WelcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DisplayUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addComponent(TokenLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DisplayTokensLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TragamonedasGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BlackJackGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaballosGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                        .addComponent(MenuActionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TokenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayTokensLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BlackJackGameButton)
                .addGap(18, 18, 18)
                .addComponent(TragamonedasGameButton)
                .addGap(18, 18, 18)
                .addComponent(CaballosGameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuActionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        MainPanel.add(MenuPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        if(!UsernameTextField.getText().equals("AxelCas123") && !PasswordTextField.getText().equals("AxelCas123")){
            if(ManejoDeArchivos.register(UsernameTextField.getText(), PasswordTextField.getText())){
                LoginActionLabel.setText("Has sido registrado exitosamente.");
            }else{
                LoginActionLabel.setText("Hubo un problema al intentar registrate.");
            }
        }
        
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        if(!UsernameTextField.getText().equals("AxelCas123") && !PasswordTextField.getText().equals("AxelCas123")){
            if(ManejoDeArchivos.login(UsernameTextField.getText(), PasswordTextField.getText())){

                DisplayUsernameLabel.setText(Singleton.getInstance().getNombre());
                DisplayTokensLabel.setText(Integer.toString(Singleton.getInstance().getFichas()));
                
                MainPanel.removeAll();
                MainFrame.setSize(MenuPanel.getWidth(), MenuPanel.getHeight());
                MainPanel.add(MenuPanel);
                
            }else{
                LoginActionLabel.setText("Hubo un problema al intentar iniciar tu sesión.");
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTextFieldFocusGained
        if(UsernameTextField.getText().equals("AxelCas123")){
            UsernameTextField.setText("");
            UsernameTextField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_UsernameTextFieldFocusGained

    private void PasswordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordTextFieldFocusGained
        if(PasswordTextField.getText().equals("AxelCas123")){
            PasswordTextField.setText("");
            PasswordTextField.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_PasswordTextFieldFocusGained

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void CaballosGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaballosGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaballosGameButtonActionPerformed

    private void BlackJackGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackJackGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlackJackGameButtonActionPerformed

    private void TragamonedasGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TragamonedasGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TragamonedasGameButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        if(ManejoDeArchivos.logout()){
            MainPanel.removeAll();
            MainFrame.setSize(LoginPanel.getWidth(), LoginPanel.getHeight());
            MainPanel.add(MenuPanel);
        }else{
            MenuActionLabel.setText("Hubo un error al intentar cerrar tu sesión");
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ManejoDeArchivos.initialize();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               SignIn_SignUp MainFrame = new SignIn_SignUp();
               MainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackJackGameButton;
    private javax.swing.JButton CaballosGameButton;
    private javax.swing.JLabel DisplayTokensLabel;
    private javax.swing.JLabel DisplayUsernameLabel;
    private javax.swing.JLabel LoginActionLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MenuActionLabel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TokenLabel;
    private javax.swing.JButton TragamonedasGameButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
    private SignIn_SignUp MainFrame;

}
